[build]
builder = "nixpacks"
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
startCommand = "gunicorn student_management_system.wsgi:application --timeout 120"
healthcheckPath = "/"
healthcheckTimeout = 300

[phases.setup]
nixPkgs = ['python39', 'postgresql', 'zlib', 'libjpeg', 'libpng', 'gcc']

[phases.install]
cmds = ['pip install --no-cache-dir -r requirements.txt']